spring:
  profiles:
    active: dev
  application:
    name: user-actions-service
  jpa:
    open-in-view: false
  liquibase:
    change-log: db/changelog/db.changelog-master.yml

server:
  port: 8082
mq:
  exchange: ums-exchange
  rout:
    task-confirmed: task-confirmed