spring:
  application:
    name: user-actions-service
  jpa:
    open-in-view: false
  liquibase:
    change-log: db/changelog/db.changelog-master.yml
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://ums-service:8081/api/token/jwks

server:
  port: 8082
mq:
  exchange: ums-exchange
  rout:
    task-confirmed: task-confirmed