name: dev-mob-ums
services:
  dev-postgres:
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_USER=developer"
      - "POSTGRES_PASSWORD=developer"
      - "POSTGRES_DB=developer"
  dev-redis:
    image: redis
    ports:
      - "6380:6379"