services:
  dev-postgres:
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=mobhackcor
      - POSTGRES_PASSWORD=mobhackcor
      - POSTGRES_DB=userdb
  dev-redis:
    image: redis
    ports:
      - "6380:6379"