spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://ums-service:8081/api/token/jwks
  docker:
    compose:
      enabled: false

minio:
  access-key: mobhackcor
  secret-key: mobhackcor
  endpoint: http://fs-minio:9000
  endpoint-override: http://localhost:9000
  url:
    time-to-live: 7
  default-bucket: mobhackcor-bucket