spring:
  application:
    name: user-management-service
  profiles:
    active: prod
server:
  port: 8081

custom:
  code:
    ttl-minutes: 5
  jwt:
    ttl-hours: 12
    refresh-ttl-days: 7
    keySize: 2048
    privateKeyPath: /tmp/private.key
    publicKeyPath: /tmp/public.key
    kidPath: /tmp/kid.txt
  query:
    rating:
      limit: 10

mq:
  queue:
    task-reward: task-reward-queue


