spring:
  application:
    name: user-management-service
  profiles:
    active: prod
server:
  port: 8081

custom:
  jwt:
    ttl-hours: 12
    refresh-ttl-days: 7
    keySize: 2048
    privateKeyPath: /tmp/private.key
    publicKeyPath: /tmp/public.key
    kidPath: /tmp/kid.txt

mq:
  queue:
    task-reward: task-reward-queue