spring:
  application:
    name: user-management-service
  docker:
    compose:
      enabled: true
      file: ./user-management-service/docker-compose.yml
  data:
    redis:
      url: ${SPRING_DATA_REDIS_URL}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  liquibase:
    change-log: db/changelog/db.changelog-master.yml
  jpa:
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://ums-service:8081/api/token/jwks


server:
  port: 8081

custom:
  jwt:
    ttl-hours: 12
    refresh-ttl-days: 7
    keySize: 2048
    privateKeyPath: /tmp/private.key
    publicKeyPath: /tmp/public.key
    kidPath: /tmp/kid.txt

mq:
  queue:
    task-reward: task-reward-queue